startdatum: "2025-06-15"

smtp:
  host: smtp.gmail.com
  port: 587
  user: henning.emmrich@gmail.com
  to: henningemmrich@icloud.com
  subject: Wetterwarnung GR20

schwellen:
  regen: 50
  gewitter: 30
  delta_prozent: 20
  hitze: 32
  wind: 40
  gewitter_ab_uhrzeit: 12